### ISSUE TITLE
关于其中控制器的问题

### ISSUE THREAD

**Issue by Jiangmmc** [wlgc1801lzh/base-admin-layui#1]
您好！很感谢您的分享，关于其中控制器的访问有一些问题想向您请教：
我重新在menu写了一个测试接口hello:

```
@RequestMapping("/menu")
public class MenuController {
    @PostMapping("/list")
    public Result list() {
        List<Menu> menus = menuService.findAll();
        return new Table(RetCode.TABLE_OK, menus, menus.size());
    }
    @PostMapping("/hello")
    public Result hello(){
        return new Result(RetCode.OK);
    }
```
我通过postman访问`menu/list`可以成功访问，但是访问`menu/hello`或者其他新写的控制器接口，都会报
` Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' not supported]`
这样的错误，换成@`GetMapping`也会报不支持‘GET‘的错误，想向您请教一下这是为什么呢？万分感谢！

**Comment by Jiangmmc** [comment]
多次尝试发现只有在菜单管理中配置过菜单路径的api才能被访问，请问这段编码是在哪里体现呢？可以怎么修改呢？谢谢！

**Comment by wlgc1801lzh** [comment]
不好意思刚看到你的问题，hui.base.interceptor这个包下面有两个拦截器，LoginInterceptor是登录拦截器，AuthInterceptor.java是权限拦截器，你看一下新添加的接口是不是没配置权限，可以手动在数据库添加关联。本地测试可以先把hui.base.config包下的WebConfig里的拦截器配置注释，暂时关闭拦截器的功能。

**Comment by Jiangmmc** [comment]
> 不好意思刚看到你的问题，hui.base.interceptor这个包下面有两个拦截器，LoginInterceptor是登录拦截器，AuthInterceptor.java是权限拦截器，你看一下新添加的接口是不是没配置权限，可以手动在数据库添加关联。本地测试可以先把hui.base.config包下的WebConfig里的拦截器配置注释，暂时关闭拦截器的功能。
已经解决啦，万分感谢！
